name: GitHub Ubuntu deploy
run-name: ${{ github.actor }} is pushing to branch 🚀
on: [push]
jobs:
  Deploy-To-ubuntu-latest:
    deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build .NET
        working-directory: ./WebPortfolio/WebApp
        uses: dotnet build 
      - name: Publish application
        run: dotnet publish -c Release -o publish/
          # name: Copy files to server
          # uses: student/scp-action@main
          #     with:
          #         host: ${{ env.SERVER_IP }}
          #         username: ${{ env.USERNAME }}
          #         key: ${{ secrets.SERVER_KEY }}
          #         source: publish/
          #         target: ${{ env.REMOTE_DIRECTORY }